1. it will print out the value of i. which is 3. This is beacuse it was made with var. therefore, even though it was made in the for loop. itll still exist outside the code block it was made.
2. It will print out its value and not throw and error because it was made using var. this means that it can exist outside of its code block. it was made in the for-loop but can exist outside of it.
3. itll print out its value for the same reasons as number 2
4. the function returns an array that is the new discounted prices. the orignals were 100, 200, 300 and then they were each dicounted by 50% and therefore the array of discounted prices is 50, 100, 150.
5. It will error because i was made using the let keyword. unlike var, let does now allow the variables it makes to cut through code blocks. therefore it was made in the for-loop so it ceases to exist once the the for-loop ends.
6.  it wont work for the same reasons above.
7.  it will work because finalPrice was made in the same scope as the console.log call. 
8.  it returns an array of the discounted prices just like the last time this question was asked. since the return call is not happening outside of the code block that discounted was made, it works just fine
9.  